/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regalapp;

/**
 *
 * @author sanik
 */
public class coursesinfoJframe extends javax.swing.JFrame {

    /**
     * Creates new form coursesinfoJframe
     */
    public coursesinfoJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnC = new javax.swing.JButton();
        btnCPP = new javax.swing.JButton();
        btnDSA = new javax.swing.JButton();
        btnADS = new javax.swing.JButton();
        btnJAVA = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlC = new javax.swing.JPanel();
        lblC = new javax.swing.JLabel();
        pnlCPP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlDSA = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlADS = new javax.swing.JPanel();
        lblADS = new javax.swing.JLabel();
        pnlJAVA = new javax.swing.JPanel();
        lblJAVA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnCPP.setText("CPP");
        btnCPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPPActionPerformed(evt);
            }
        });

        btnDSA.setText("DSA");
        btnDSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSAActionPerformed(evt);
            }
        });

        btnADS.setText("ADS");
        btnADS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADSActionPerformed(evt);
            }
        });

        btnJAVA.setText("JAVA");
        btnJAVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJAVAActionPerformed(evt);
            }
        });

        pnlC.setBackground(new java.awt.Color(51, 51, 51));
        pnlC.setForeground(new java.awt.Color(255, 255, 255));

        lblC.setForeground(new java.awt.Color(255, 255, 255));
        lblC.setText("About C");

        pnlCPP.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("About CPP");

        pnlDSA.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("About DSA");

        pnlADS.setBackground(new java.awt.Color(204, 204, 204));

        lblADS.setForeground(new java.awt.Color(255, 255, 255));
        lblADS.setText("About ADS");

        pnlJAVA.setForeground(new java.awt.Color(204, 204, 204));

        lblJAVA.setText("About JAVA");

        javax.swing.GroupLayout pnlJAVALayout = new javax.swing.GroupLayout(pnlJAVA);
        pnlJAVA.setLayout(pnlJAVALayout);
        pnlJAVALayout.setHorizontalGroup(
            pnlJAVALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJAVALayout.createSequentialGroup()
                .addComponent(lblJAVA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlJAVALayout.setVerticalGroup(
            pnlJAVALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJAVALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJAVA)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlADSLayout = new javax.swing.GroupLayout(pnlADS);
        pnlADS.setLayout(pnlADSLayout);
        pnlADSLayout.setHorizontalGroup(
            pnlADSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlADSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblADS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlJAVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlADSLayout.setVerticalGroup(
            pnlADSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlADSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblADS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlJAVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDSALayout = new javax.swing.GroupLayout(pnlDSA);
        pnlDSA.setLayout(pnlDSALayout);
        pnlDSALayout.setHorizontalGroup(
            pnlDSALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDSALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlADS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDSALayout.setVerticalGroup(
            pnlDSALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDSALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlADS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCPPLayout = new javax.swing.GroupLayout(pnlCPP);
        pnlCPP.setLayout(pnlCPPLayout);
        pnlCPPLayout.setHorizontalGroup(
            pnlCPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCPPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlDSA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCPPLayout.setVerticalGroup(
            pnlCPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCPPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDSA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCLayout = new javax.swing.GroupLayout(pnlC);
        pnlC.setLayout(pnlCLayout);
        pnlCLayout.setHorizontalGroup(
            pnlCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
            .addComponent(pnlCPP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCLayout.setVerticalGroup(
            pnlCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCLayout.createSequentialGroup()
                .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(pnlC, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnCPP)
                .addGap(33, 33, 33)
                .addComponent(btnDSA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnADS)
                .addGap(44, 44, 44)
                .addComponent(btnJAVA)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnC)
                    .addComponent(btnCPP)
                    .addComponent(btnJAVA)
                    .addComponent(btnADS)
                    .addComponent(btnDSA))
                .addGap(36, 36, 36)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        pnlC.setVisible(true);
        pnlADS.setVisible(false);
        pnlDSA.setVisible(false);
        pnlJAVA.setVisible(false);
        pnlCPP.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCActionPerformed

    private void btnCPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPPActionPerformed
       pnlCPP.setVisible(true);
        pnlC.setVisible(false);
        pnlADS.setVisible(false);
        pnlDSA.setVisible(false);
        pnlJAVA.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCPPActionPerformed

    private void btnDSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSAActionPerformed
         pnlDSA.setVisible(true);
        pnlC.setVisible(false);
        pnlADS.setVisible(false);
       
        pnlJAVA.setVisible(false);
        pnlCPP.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnDSAActionPerformed

    private void btnADSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADSActionPerformed
         pnlADS.setVisible(true);
        pnlC.setVisible(false);
       
        pnlDSA.setVisible(false);
        pnlJAVA.setVisible(false);
        pnlCPP.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnADSActionPerformed

    private void btnJAVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJAVAActionPerformed
       pnlJAVA.setVisible(true);
        pnlC.setVisible(false);
        pnlADS.setVisible(false);
        pnlDSA.setVisible(false);
       
        pnlCPP.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_btnJAVAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coursesinfoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coursesinfoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coursesinfoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coursesinfoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coursesinfoJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADS;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCPP;
    private javax.swing.JButton btnDSA;
    private javax.swing.JButton btnJAVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblADS;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblJAVA;
    private javax.swing.JPanel pnlADS;
    private javax.swing.JPanel pnlC;
    private javax.swing.JPanel pnlCPP;
    private javax.swing.JPanel pnlDSA;
    private javax.swing.JPanel pnlJAVA;
    // End of variables declaration//GEN-END:variables
}
