/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regalapp;

/**
 *
 * @author sanik
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    public MainJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmian = new javax.swing.JPanel();
        btnaddmission = new javax.swing.JButton();
        btnenquiry1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlmian.setBackground(new java.awt.Color(0, 0, 0));

        btnaddmission.setBackground(new java.awt.Color(0, 0, 0));
        btnaddmission.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        btnaddmission.setForeground(new java.awt.Color(255, 255, 255));
        btnaddmission.setText("ADDMISSION");
        btnaddmission.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.yellow, java.awt.Color.yellow, new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        btnaddmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddmissionActionPerformed(evt);
            }
        });

        btnenquiry1.setBackground(new java.awt.Color(0, 0, 0));
        btnenquiry1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        btnenquiry1.setForeground(new java.awt.Color(255, 255, 255));
        btnenquiry1.setText("ENQUIRY");
        btnenquiry1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.yellow, java.awt.Color.yellow, new java.awt.Color(255, 255, 204), new java.awt.Color(255, 255, 204)));
        btnenquiry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenquiry1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlmianLayout = new javax.swing.GroupLayout(pnlmian);
        pnlmian.setLayout(pnlmianLayout);
        pnlmianLayout.setHorizontalGroup(
            pnlmianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmianLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnaddmission, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(pnlmianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlmianLayout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(btnenquiry1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE)))
        );
        pnlmianLayout.setVerticalGroup(
            pnlmianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmianLayout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(btnaddmission, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(pnlmianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlmianLayout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(btnenquiry1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddmissionActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddmissionActionPerformed

    private void btnenquiry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenquiry1ActionPerformed
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentypeJframe().setVisible(true);
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_btnenquiry1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddmission;
    private javax.swing.JButton btnenquiry1;
    private javax.swing.JPanel pnlmian;
    // End of variables declaration//GEN-END:variables
}
