/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regalapp;
import java.awt.CheckboxGroup;
import java.sql.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author sanik
 */
public class newstudentinfoJframe extends javax.swing.JFrame {

    /**
     * Creates new form newstudentinfoJframe
     */
    WEBCAMJFRAME1 ref;
    int hometownid,collageid;
    String gender;
    String Localadd;
    
    public newstudentinfoJframe() {
        ref=new WEBCAMJFRAME1();
        initComponents();
chbhometown.removeAllItems();
chbcollage.removeAllItems();
//          
chbhometown.addItem("");
        chbhometown.addItem("Sangli");
        chbhometown.addItem("Pune");
           chbhometown.addItem("Mumbai");
        chbhometown.addItem("Kolhapur");
        chbhometown.addItem("Satara");
//                chbhometown.removeItemAt(0);
//         chbhometown.removeItemAt(1);
//          chbhometown.removeItemAt(2);
//           chbhometown.removeItemAt(3);
//           chbhometown.removeItemAt(4);
          // chbhometown.removeItemAt(5);
         chbcollage.addItem("");
         chbcollage.addItem("PICT");
        chbcollage.addItem("COEP");
           chbcollage.addItem("VIT");
        chbcollage.addItem("VIIT");
        chbcollage.addItem("PVG");
      
    }
    CheckboxGroup cbg=new CheckboxGroup();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlmain = new javax.swing.JPanel();
        pnlsub = new javax.swing.JPanel();
        txtfname = new javax.swing.JTextField();
        lblfname = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        lbllname = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtphoneno = new javax.swing.JTextField();
        lblemail1 = new javax.swing.JLabel();
        lblgender = new javax.swing.JLabel();
        chkmale = new javax.swing.JRadioButton();
        chkfemale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtlocaladdress = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnsameaslocal = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpermanentaddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblbirthdate = new javax.swing.JLabel();
        lblhometown = new javax.swing.JLabel();
        lblcollage = new javax.swing.JLabel();
        lblcourses = new javax.swing.JLabel();
        chkC = new javax.swing.JCheckBox();
        chkCPP = new javax.swing.JCheckBox();
        chkDSA = new javax.swing.JCheckBox();
        chkADS = new javax.swing.JCheckBox();
        chkJAVA = new javax.swing.JCheckBox();
        btnmoreinfo = new javax.swing.JButton();
        btnaddphoto = new javax.swing.JButton();
        bdate = new com.toedter.calendar.JDateChooser();
        pnlphoto = new javax.swing.JPanel();
        lblphoto1 = new javax.swing.JLabel();
        chbhometown = new javax.swing.JComboBox<>();
        chbcollage = new javax.swing.JComboBox<>();
        btnsubmit = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlmain.setBackground(new java.awt.Color(0, 0, 0));

        pnlsub.setBackground(new java.awt.Color(255, 255, 204));

        txtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfnameKeyTyped(evt);
            }
        });

        lblfname.setText("First Name");

        txtlname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlnameKeyTyped(evt);
            }
        });

        lbllname.setText("Last Name");

        lblemail.setText("Email");

        txtphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphonenoKeyTyped(evt);
            }
        });

        lblemail1.setText("Phone Number");

        lblgender.setText("Gender");

        chkmale.setText("Male");
        chkmale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkmaleItemStateChanged(evt);
            }
        });

        chkfemale.setText("Female");
        chkfemale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkfemaleItemStateChanged(evt);
            }
        });
        chkfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkfemaleActionPerformed(evt);
            }
        });

        txtlocaladdress.setColumns(20);
        txtlocaladdress.setRows(5);
        jScrollPane1.setViewportView(txtlocaladdress);

        jLabel3.setText("Local Address");

        btnsameaslocal.setText(">>");
        btnsameaslocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsameaslocalActionPerformed(evt);
            }
        });

        btnclear.setText("<<");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        txtpermanentaddress.setColumns(20);
        txtpermanentaddress.setRows(5);
        jScrollPane2.setViewportView(txtpermanentaddress);

        jLabel4.setText("Permanent Address");

        lblbirthdate.setText("Birth date");

        lblhometown.setText("Hometown");

        lblcollage.setText("Collage");

        lblcourses.setText("Courses");

        chkC.setText("C");
        chkC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCActionPerformed(evt);
            }
        });

        chkCPP.setText("CPP");

        chkDSA.setText("DSA");

        chkADS.setText("ADS");
        chkADS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkADSActionPerformed(evt);
            }
        });

        chkJAVA.setText("JAVA");
        chkJAVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJAVAActionPerformed(evt);
            }
        });

        btnmoreinfo.setBackground(new java.awt.Color(255, 153, 153));
        btnmoreinfo.setForeground(new java.awt.Color(255, 255, 51));
        btnmoreinfo.setText("Click for More Information");
        btnmoreinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoreinfoActionPerformed(evt);
            }
        });

        btnaddphoto.setBackground(new java.awt.Color(255, 153, 153));
        btnaddphoto.setForeground(new java.awt.Color(255, 255, 51));
        btnaddphoto.setText("Click here to add photo");
        btnaddphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddphotoActionPerformed(evt);
            }
        });

        pnlphoto.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlphotoLayout = new javax.swing.GroupLayout(pnlphoto);
        pnlphoto.setLayout(pnlphotoLayout);
        pnlphotoLayout.setHorizontalGroup(
            pnlphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlphotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblphoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlphotoLayout.setVerticalGroup(
            pnlphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblphoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );

        chbhometown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chbhometown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbhometownItemStateChanged(evt);
            }
        });
        chbhometown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbhometownActionPerformed(evt);
            }
        });

        chbcollage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chbcollage.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbcollageItemStateChanged(evt);
            }
        });
        chbcollage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbcollageActionPerformed(evt);
            }
        });

        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlsubLayout = new javax.swing.GroupLayout(pnlsub);
        pnlsub.setLayout(pnlsubLayout);
        pnlsubLayout.setHorizontalGroup(
            pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsubLayout.createSequentialGroup()
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnsameaslocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlsubLayout.createSequentialGroup()
                                .addComponent(lblhometown, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(lblcollage, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(lblbirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(lblcourses, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(69, 69, 69))
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblgender, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsubLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(chkfemale))))
                            .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlsubLayout.createSequentialGroup()
                                    .addComponent(lbllname, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtlname))
                                .addGroup(pnlsubLayout.createSequentialGroup()
                                    .addComponent(lblfname, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlsubLayout.createSequentialGroup()
                                    .addComponent(lblemail1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkmale, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtphoneno)))))
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlsubLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnaddphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chbhometown, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsubmit))
                        .addGap(18, 18, 18)
                        .addComponent(chbcollage, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addComponent(chkADS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkJAVA))
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addComponent(chkC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkCPP, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkDSA, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnmoreinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(39, 39, 39))))
        );
        pnlsubLayout.setVerticalGroup(
            pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfname)
                            .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbllname))
                        .addGap(18, 18, 18)
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblemail1)
                            .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblgender)
                            .addComponent(chkmale)
                            .addComponent(chkfemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblemail)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addComponent(pnlphoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnaddphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addComponent(btnsameaslocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnclear))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addComponent(lblcollage)
                        .addGap(226, 226, 226))
                    .addGroup(pnlsubLayout.createSequentialGroup()
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addComponent(lblbirthdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlsubLayout.createSequentialGroup()
                                        .addComponent(lblhometown)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(chbhometown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chbcollage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlsubLayout.createSequentialGroup()
                                        .addComponent(lblcourses)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(chkC)
                                            .addComponent(chkCPP)
                                            .addComponent(chkDSA))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkADS)
                            .addComponent(chkJAVA))
                        .addGroup(pnlsubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnmoreinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlsubLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnsubmit)))
                        .addGap(121, 121, 121))))
        );

        lbltitle.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("FILL DETAILS");

        javax.swing.GroupLayout pnlmainLayout = new javax.swing.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pnlsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlmainLayout.setVerticalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlsub, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkfemaleActionPerformed
 
// TODO add your handling code here:
    }//GEN-LAST:event_chkfemaleActionPerformed

    private void btnsameaslocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsameaslocalActionPerformed
    
        Localadd=txtlocaladdress.getText();
        txtpermanentaddress.setText(Localadd);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsameaslocalActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtpermanentaddress.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void chkCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCActionPerformed

    private void chkADSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkADSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkADSActionPerformed

    private void chkJAVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJAVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkJAVAActionPerformed

    private void btnmoreinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoreinfoActionPerformed
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coursesinfoJframe().setVisible(true);
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmoreinfoActionPerformed

    private void btnaddphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddphotoActionPerformed
       // WEBCAMJFRAME1 ref=new WEBCAMJFRAME1();
       // ref.setVisible(true);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WEBCAMJFRAME1().setVisible(true);
            }
        });
       Image img1=ref.getImage123();
       lblphoto1.setIcon(new ImageIcon(img1));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddphotoActionPerformed

    private void txtfnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyTyped
        char ch;
        ch=evt.getKeyChar();
        if(Character.isAlphabetic(ch)==false)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameKeyTyped

    private void txtlnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlnameKeyTyped
         char ch;
        ch=evt.getKeyChar();
        if(Character.isAlphabetic(ch)==false)
        {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameKeyTyped

    private void txtphonenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphonenoKeyTyped
        char ch;
        ch=evt.getKeyChar();
        
        if(Character.isDigit(ch)==false || phonenumberc>11)
        {
            evt.consume();
        }
        else
        {
            phonenumberc++;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonenoKeyTyped

    private void chbcollageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbcollageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbcollageActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed

        try {         SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
                       String str=sdf.format(bdate.getDate());
                      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/regalapp","root","sa123");
                        Statement st=con.createStatement();
                        String query="INSERT INTO `regalapp`.`new_student` ( `fname`, `lname`, `email`, `birthdate`, `localaddress`, `permanentaddress`, `gender`, `hometownid`, `collageid`) VALUES ('"+txtfname.getText()+"', '"+txtlname.getText()+"', '"+txtemail.getText()+"', '"+str+"', '"+txtlocaladdress.getText()+"', '"+txtpermanentaddress.getText()+"', '"+gender+"', '"+hometownid+"', '"+collageid+"')";
                       // String query1="insert into new_student(fname,lname,email,birthdate,localaddress,permanentaddress,gender,hometownid,collageid)values('"+txtfname.getText()+"','"+txtlname.getText()+"','"+txtemail.getText()+"','"+str+"','"+txtlocaladdress.getText()+"','"+txtpermanentaddress.getText()+"','"+gender+"','"+hometownid+"','"+collageid+")";
                        st.executeUpdate(query);
                        System.out.println("hiiiiiiiiiii i reached here tooo");
                        JOptionPane.showMessageDialog(this,"inserted succesfully!!!"+gender);
        } catch (Exception e) {
                                    JOptionPane.showMessageDialog(this,e);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void chbhometownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbhometownItemStateChanged

        
        hometownid=chbhometown.getSelectedIndex();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_chbhometownItemStateChanged

    private void chbcollageItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbcollageItemStateChanged
        collageid=chbcollage.getSelectedIndex();
        // TODO add your handling code here:
    }//GEN-LAST:event_chbcollageItemStateChanged

    private void chkmaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkmaleItemStateChanged
        gender="M";
        // TODO add your handling code here:
    }//GEN-LAST:event_chkmaleItemStateChanged

    private void chkfemaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkfemaleItemStateChanged
        gender="F";
        // TODO add your handling code here:
    }//GEN-LAST:event_chkfemaleItemStateChanged

    private void chbhometownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbhometownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbhometownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newstudentinfoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newstudentinfoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newstudentinfoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newstudentinfoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newstudentinfoJframe().setVisible(true);
            }
        });
    }
    
    
    int phonenumberc=0;
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser bdate;
    private javax.swing.JButton btnaddphoto;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnmoreinfo;
    private javax.swing.JButton btnsameaslocal;
    private javax.swing.JButton btnsubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> chbcollage;
    private javax.swing.JComboBox<String> chbhometown;
    private javax.swing.JCheckBox chkADS;
    private javax.swing.JCheckBox chkC;
    private javax.swing.JCheckBox chkCPP;
    private javax.swing.JCheckBox chkDSA;
    private javax.swing.JCheckBox chkJAVA;
    private javax.swing.JRadioButton chkfemale;
    private javax.swing.JRadioButton chkmale;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblbirthdate;
    private javax.swing.JLabel lblcollage;
    private javax.swing.JLabel lblcourses;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblemail1;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblhometown;
    private javax.swing.JLabel lbllname;
    private javax.swing.JLabel lblphoto1;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JPanel pnlmain;
    private javax.swing.JPanel pnlphoto;
    private javax.swing.JPanel pnlsub;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextArea txtlocaladdress;
    private javax.swing.JTextArea txtpermanentaddress;
    private javax.swing.JTextField txtphoneno;
    // End of variables declaration//GEN-END:variables
}
