/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package regalapp;
import java.sql.*;
import com.github.sarxos.webcam.Webcam;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sanik
 */
public class WEBCAMJFRAME1 extends javax.swing.JFrame  {

    /**
     * Creates new form WEBCAMJFRAME1
     */
  //craete obj of Webcam and import 1st{1}
    Webcam webcam;
   // newstudentinfoJframe obj;
    volatile boolean value;
  //  newstudentinfoJframe ref;
    public WEBCAMJFRAME1() {
       
        initComponents();
       // this.obj=obj;
        webcam=Webcam.getDefault();//connect laptop cam {2}
        webcam.setViewSize(new Dimension(640,480));//set dimetion of WebCam{3}je dimention set karyche ahet tech karche execption madhe yetay 
        
    }
    public  Image getImage123()
    {
        Image img=webcam.getImage();
        if(img!=null)
        {
            return img;
        }
       return img;
    }
 /*public void run()//implemet Runnable and define run(){7}
    {
        while(value)//to see video wala effect{10}
        {
            Image img=webcam.getImage();
            if(img!=null)
            {
                //set as a icon{6}
            }   
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlmain = new javax.swing.JPanel();
        btncapture = new javax.swing.JButton();
        lblcapture = new javax.swing.JLabel();
        btnstart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlmain.setBackground(new java.awt.Color(255, 204, 204));

        btncapture.setText("CAPTURE");
        btncapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaptureActionPerformed(evt);
            }
        });

        lblcapture.setBackground(new java.awt.Color(255, 255, 255));
        lblcapture.setOpaque(true);

        btnstart.setText("STRAT CAM");
        btnstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlmainLayout = new javax.swing.GroupLayout(pnlmain);
        pnlmain.setLayout(pnlmainLayout);
        pnlmainLayout.setHorizontalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmainLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlmainLayout.createSequentialGroup()
                        .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btncapture, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblcapture, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pnlmainLayout.setVerticalGroup(
            pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmainLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblcapture, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncapture, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnstart, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaptureActionPerformed

        try
        {
            webcam.open();
            Image img=webcam.getImage();
           // value=false;
            //obj.lblphoto1.setIcon(new ImageIcon(img));//set as a icon{6}
            ImageIO.write(webcam.getImage(),"PNG",new File("E:\\Regal_class_JAVA\\Regal_Application\\RegalApp\\src\\StudentImage\\images.jpeg"));//new file on mentioned path img store karychi ahe
            FileInputStream fin=new FileInputStream("E:\\Regal_class_JAVA\\Regal_Application\\RegalApp\\src\\StudentImage\\images.jpeg");
            webcam.close();

            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/webcam","root","sa123");
            PreparedStatement pst=con.prepareStatement("insert into images(imgpath) values(?)");
            pst.setBlob(1,fin);
            pst.execute();
            JOptionPane.showMessageDialog(this,"img saved");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btncaptureActionPerformed

    private void btnstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstartActionPerformed

        //define thread and starrt it{8}

        webcam.open();//open the webcam{4}
       // Thread t=new Thread(this);
       // t.start();
       // value=true;
        // TODO add your handling code here:
    }//GEN-LAST:event_btnstartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WEBCAMJFRAME1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WEBCAMJFRAME1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WEBCAMJFRAME1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WEBCAMJFRAME1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WEBCAMJFRAME1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapture;
    private javax.swing.JButton btnstart;
    private javax.swing.JLabel lblcapture;
    private javax.swing.JPanel pnlmain;
    // End of variables declaration//GEN-END:variables
}
